apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image }}:{{ .Values.postgres.version }}"
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.postgres.db.name }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgres.db.user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgres.db.password }}"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "{{ .Values.postgres.resources.requests.cpu }}"
            memory: "{{ .Values.postgres.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.postgres.resources.limits.cpu }}"
            memory: "{{ .Values.postgres.resources.limits.memory }}"
        startupProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgres.db.user }}
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 20
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgres.db.user }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgres.db.user }}
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
      {{- if .Values.postgres.persistence.enabled }}
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      {{- end }}
