apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "mlservice"
        - name: POSTGRES_USER
          value: "mlservice"
        - name: POSTGRES_PASSWORD
          value: "mlservice"
        startupProbe:
          exec:
            command:
            - pg_isready
            - -U
            - mlservice
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 20
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - mlservice
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - mlservice
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
